requires 'Class::Component' => '0.17';
requires 'Furl';
requires 'Params::Validate' => 0.91;
requires 'YAML';
requires 'IO::Socket::INET';
requires 'Socket';
requires 'IO::Select';
requires 'IO::Socket::SSL';
requires 'Net::SSH';
requires 'IPC::Open3';
requires 'Kwalify';
requires 'Pod::POM';
requires 'List::Util';
requires 'Log::Dispatch';
requires 'Net::SNMP';
